import type { GeneratedSchemas, ExportConfig } from '../types.js';

const DEFAULT_HEADER = '// AUTO-GENERATED — DO NOT EDIT';

export function generateTypescriptRegistry(
  schemas: GeneratedSchemas[],
  config: Partial<ExportConfig> = {},
): string {
  const header = config.fileHeader || DEFAULT_HEADER;
  const lines: string[] = [];

  lines.push(header);
  lines.push(`// Generated by storybook-addon-zod-schemas on ${new Date().toISOString()}`);
  lines.push('');

  if (config.includeVercelAISDK) {
    lines.push("import { tool } from 'ai';");
  }

  for (const schema of schemas) {
    lines.push(`import { ${schema.componentName}Schema } from './schemas/${schema.componentName}';`);
  }

  lines.push('');

  if (config.includeVercelAISDK) {
    lines.push('export const componentRegistry = {');
    for (const schema of schemas) {
      const desc = schema.description || `${schema.componentName} component`;
      lines.push(`  ${schema.componentName}: tool({`);
      lines.push(`    description: '${desc}',`);
      lines.push(`    parameters: ${schema.componentName}Schema,`);
      lines.push('  }),');
    }
    lines.push('};');
  } else {
    lines.push('export const componentRegistry = {');
    for (const schema of schemas) {
      lines.push(`  ${schema.componentName}: ${schema.componentName}Schema,`);
    }
    lines.push('};');
  }

  lines.push('');
  lines.push('export type ComponentName = keyof typeof componentRegistry;');
  lines.push('');

  if (config.includeTamboRegistration) {
    lines.push('// Tambo-compatible component registration');
    lines.push('export const tamboComponents = [');
    for (const schema of schemas) {
      const desc = schema.description || `${schema.componentName} component`;
      lines.push('  {');
      lines.push(`    name: '${schema.componentName}',`);
      lines.push(`    description: '${desc}',`);
      lines.push(`    propsSchema: ${schema.componentName}Schema,`);
      lines.push('  },');
    }
    lines.push('];');
    lines.push('');
  }

  return lines.join('\n');
}

export function generatePythonRegistry(
  schemas: GeneratedSchemas[],
  config: Partial<ExportConfig> = {},
): string {
  const header = config.fileHeader
    ? config.fileHeader.replace(/^\/\//gm, '#')
    : '# AUTO-GENERATED — DO NOT EDIT';
  const lines: string[] = [];

  lines.push(header);
  lines.push(`# Generated by storybook-addon-zod-schemas on ${new Date().toISOString()}`);
  lines.push('');
  lines.push('from typing import Union');

  for (const schema of schemas) {
    const moduleName = schema.componentName
      .replace(/([a-z])([A-Z])/g, '$1_$2')
      .toLowerCase();
    lines.push(
      `from .components.${moduleName} import ${schema.componentName}Component`,
    );
  }

  lines.push('');
  lines.push('');

  // Union type
  lines.push('UIComponent = Union[');
  for (const schema of schemas) {
    lines.push(`    ${schema.componentName}Component,`);
  }
  lines.push(']');
  lines.push('');
  lines.push('');

  // Registry dict
  lines.push('COMPONENT_REGISTRY = {');
  for (const schema of schemas) {
    lines.push(`    "${schema.componentName}": ${schema.componentName}Component,`);
  }
  lines.push('}');
  lines.push('');
  lines.push('');

  // Helper functions
  lines.push('def get_all_schemas() -> dict:');
  lines.push('    """Get all component schemas for LLM tool calling"""');
  lines.push('    return {');
  lines.push('        name: cls.model_json_schema()');
  lines.push('        for name, cls in COMPONENT_REGISTRY.items()');
  lines.push('    }');
  lines.push('');
  lines.push('');
  lines.push('def get_component_schema(component_type: str) -> dict:');
  lines.push('    """Get JSON schema for specific component"""');
  lines.push('    if component_type not in COMPONENT_REGISTRY:');
  lines.push('        raise ValueError(f"Unknown component: {component_type}")');
  lines.push('    return COMPONENT_REGISTRY[component_type].model_json_schema()');
  lines.push('');

  return lines.join('\n');
}
